#include "main.h"

const TILE_INFO TILE_INFOS[TILE_COUNT] =
{
	{0, 0},                                  // Null
	{TEXTURE_TEST, 0},                       // Test
	{TEXTURE_STONE_BRICKS, TILE_FLAGS_WALL}, // Stone bricks
	{TEXTURE_WOOD_PLANKS, 0},                // Wood planks
};

const TILE ROOM[16][16] = {
	{TILE_TEST,             TILE_STONE_BRICK_WALL, TILE_NULL,             TILE_NULL,             TILE_NULL,             TILE_NULL,             TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL},
	{TILE_STONE_BRICK_WALL, TILE_WOOD_PLANKS,      TILE_STONE_BRICK_WALL, TILE_NULL,             TILE_NULL,             TILE_NULL,             TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL},
	{TILE_STONE_BRICK_WALL, TILE_WOOD_PLANKS,      TILE_STONE_BRICK_WALL, TILE_NULL,             TILE_NULL,             TILE_NULL,             TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL},
	{TILE_STONE_BRICK_WALL, TILE_WOOD_PLANKS,      TILE_STONE_BRICK_WALL, TILE_NULL,             TILE_NULL,             TILE_NULL,             TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL},
	{TILE_STONE_BRICK_WALL, TILE_WOOD_PLANKS,      TILE_STONE_BRICK_WALL, TILE_STONE_BRICK_WALL, TILE_NULL,             TILE_NULL,             TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL},
	{TILE_STONE_BRICK_WALL, TILE_WOOD_PLANKS,      TILE_WOOD_PLANKS,      TILE_WOOD_PLANKS,      TILE_STONE_BRICK_WALL, TILE_NULL,             TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL},
	{TILE_STONE_BRICK_WALL, TILE_WOOD_PLANKS,      TILE_TEST,             TILE_WOOD_PLANKS,      TILE_WOOD_PLANKS,      TILE_STONE_BRICK_WALL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL},
	{TILE_STONE_BRICK_WALL, TILE_WOOD_PLANKS,      TILE_WOOD_PLANKS,      TILE_WOOD_PLANKS,      TILE_STONE_BRICK_WALL, TILE_NULL,             TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL},
	{TILE_NULL,             TILE_STONE_BRICK_WALL, TILE_WOOD_PLANKS,      TILE_STONE_BRICK_WALL, TILE_NULL,             TILE_NULL,             TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL},
	{TILE_NULL,             TILE_NULL,             TILE_STONE_BRICK_WALL, TILE_NULL,             TILE_NULL,             TILE_NULL,             TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL},
	{TILE_NULL,             TILE_NULL,             TILE_NULL,             TILE_NULL,             TILE_NULL,             TILE_NULL,             TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL},
	{TILE_NULL,             TILE_NULL,             TILE_NULL,             TILE_NULL,             TILE_NULL,             TILE_NULL,             TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL},
	{TILE_NULL,             TILE_NULL,             TILE_NULL,             TILE_NULL,             TILE_NULL,             TILE_NULL,             TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL},
	{TILE_NULL,             TILE_NULL,             TILE_NULL,             TILE_NULL,             TILE_NULL,             TILE_NULL,             TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL},
	{TILE_NULL,             TILE_NULL,             TILE_NULL,             TILE_NULL,             TILE_NULL,             TILE_NULL,             TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL},
	{TILE_NULL,             TILE_NULL,             TILE_NULL,             TILE_NULL,             TILE_NULL,             TILE_NULL,             TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL, TILE_NULL},
};